GET http://localhost:3000/

###

GET http://localhost:3000/items

###
GET http://localhost:3000/items/item
Content-Type: application/json

{
    "itemId":"60f89467616f1d41cc04d6c4"
}

###

GET http://localhost:3000/img/pokemon-rojo.jpg

###
POST http://localhost:3000/items
Content-Type: application/json

{
    "title": "Pokemon Plata",
    "price": 19.99,
    "stock":15,
    "image": "pokemon-plata.jpg"
}

###
POST http://localhost:3000/create-payment-intent
Content-Type: application/json

[
    {
        "id": "60f89467616f1d41cc04d6c4",
        "qty": 2 // cantidad
    }
]

###
POST http://localhost:3000/order
Content-Type: application/json

{
    "email": "test@test.com",
    "items":[
        {
            "id": "5f87ebadbf386d24f40c286b",
            "qty": 2
        }
    ]
}